CREATE TABLE Users(
UserId INT IDENTITY(1,1) NOT NULL,
UserEmail NVARCHAR(256) NOT NULL,
UserPasswordSalt NVARCHAR(256) NOT NULL,
UserFirstName NVARCHAR(256) NOT NULL,
UserLastName NVARCHAR(256) NOT NULL,
UserProfilePicturePath NVARCHAR(MAX),
CONSTRAINT PK_Users PRIMARY KEY (UserId),
); 

